---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: yaml-linter-
spec:
  params:
    - name: source-repo
      value: url
  pipelineRef:
    name: linter-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce
